apps/adverts/urls.py
from django.urls import path
from apps.adverts import views as advert_views
from apps.payment import views

urlpatterns = [
    path("adverts/", advert_views.adv_list, name="adverts_list"),
    path("ad/", advert_views.AdView.as_view(), name="ad-view"),
    path("ad/<int:pk>/upload_video", advert_views.upload_video, name="upload-video"),
    path("ad/create/insta_callback", advert_views.insta_callback, name='insta_callback'),
    path("ad/new/", advert_views.ad_redirect, name="ad-new"),
    path("ad/<int:ad_id>/details", advert_views.ad_details, name="ad-details"),
    path("ad/<int:ad_id>/edit", advert_views.edit_ad, name="ad-edit"),
    path("ad/<int:pk>/subscribe", advert_views.subscribe, name="subscribe"),
    path("ad/<int:pk>/plan", views.subscription_plans, name="sub-plans"),
    path("ad/<int:pk>/delete", advert_views.ad_delete, name="delete-ad"),
    path("ad/media/<int:pk>/approve", advert_views.approve_media, name="approve-media"),
    path("ad/media/<int:pk>/reject/", advert_views.reject_media, name="reject-media"),
    path("ad/broadcast/<int:pk>/", advert_views.broadcast_advert, name="approve-media"),
]

doohma/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from apps.common import views as common_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('doohma_admin/', include('apps.doohma_admin.urls')),
    path('', include('apps.common.urls')),
    path('', include('apps.adverts.urls')),
    path('', include('apps.payment.urls')),
    url('^', include('django.contrib.auth.urls')),
    path('account/', include('apps.user.urls')),
    path('api/v1/', include('apps.api.urls')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    url(r'^404/',common_views.render_404, name="404")


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/adverts/models.py
import os
from datetime import timedelta

from django.contrib.auth import get_user_model
from django.db import models
from apps.adverts.constants import AdvertStatus, MediaType, RejectOptions
from apps.common.base_model import BaseModel
from .validators import validate_file_extension

User = get_user_model()

def get_advert_image_path(instance, filename):
    return os.path.join("advertisements/%s/%s" % (instance.id, filename))


class Advert(BaseModel):
    ad_title = models.CharField(max_length=255)
    ad_description = models.TextField()
    status = models.SmallIntegerField(choices=AdvertStatus.get_choices(), default=AdvertStatus.Pending)
    start_date = models.DateField(blank=True, null=True)
    end_date = models.DateTimeField(blank=True, null=True)
    is_paid = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_approved = models.BooleanField(default=False)
    video = models.FileField(
        "Uploaded Video",
        upload_to=get_advert_image_path,
        blank=True,
        null=True,
        validators=[validate_file_extension]
    )

    def __str__(self):
        return "{}".format(self.ad_title)

    class Meta:
        db_table = "dh_advert"
        verbose_name_plural = "Adverts"

    @property
    def video_url(self):
        if self.video and hasattr(self.video, 'url'):
            return self.video.url
        return None

    def save(self, *args, **kwargs):
        if not self.pk:
            self.end_date = self.start_date + timedelta(days=30)
        return super(Advert, self).save(*args, **kwargs)

class AdvertImages(BaseModel):
    image = models.FileField(upload_to=get_advert_image_path)
    advert = models.ForeignKey(Advert, on_delete=models.CASCADE, related_name="image_set")
    type = models.SmallIntegerField(choices=MediaType.get_choices(), default=MediaType.Image)
    is_approved = models.BooleanField(default=False)
    is_rejected = models.BooleanField(default=False)
    is_broadcast = models.BooleanField(default=False)
    reject_reason = models.IntegerField(choices=RejectOptions.get_choices(), default=RejectOptions.BAD_QUALITY)

    def __str__(self):
        return "{}".format(self.advert)

    class Meta:
        db_table = 'dh_advert_media'
        verbose_name_plural = "Adverts Medias"

apps/adverts/forms.py
import datetime
import json
import logging
import os
from django.conf import settings
from django  import forms
from django.core.files.storage import FileSystemStorage
from django.shortcuts import render
from formtools.wizard.views import SessionWizardView
from storages.backends.gcloud import GoogleCloudStorage
from django.core.files.storage import default_storage
from apps.adverts.models import Advert, AdvertImages

import base64
from django.core.files.base import ContentFile
from django.contrib.admin import widgets


logger = logging.getLogger('api')

def base64_file(data, name=None):
    _img_str = data.get('data')
    return ContentFile(base64.b64decode(_img_str), name='{}'.format(name))

class AdvertCreateForm(forms.ModelForm):
    images = forms.FileField(
        widget=forms.ClearableFileInput(attrs={'multiple': True}),
        required=False,
        help_text="Select Multiple images of high quality for best experience")
    start_date = forms.DateField(required=True)

    def clean_start_date(self):
        date = self.cleaned_data['start_date']
        if not self.instance.pk:
            if date < datetime.date.today():
                raise forms.ValidationError("The date cannot be in the past!")
        return date

    class Meta:
        model = Advert
        fields = (
            "ad_title",
            "ad_description",
            "images",
            "user",
            "start_date"
        )

    def __init__(self, *args, **kwargs):
        super(AdvertCreateForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        ad = super(AdvertCreateForm, self).save(commit=False)
        if commit:
            ad.save()
            ad.image_set.all().delete()
            x = dict(self.data.lists())
            img_strs = x.get('images')
            for idx, img in enumerate(img_strs):
                if img:
                    img = json.loads(img)
                    file_name = img.get('name') + str(idx)
                    content_type = img.get('type').split('/')[0]
                    if content_type in ['video', 'application']:
                        media_type=2
                        if len(img.get('name').split('.')) <= 1:
                            file_name += ".mp4"
                            img['type'] = 'video/mp4'
                    else:
                        media_type = 1
                        file_name += ".png"
                    m = GoogleCloudStorage(location=os.path.join('ads/{}'.format(ad.id)))
                    path = m.save(file_name, base64_file(img))
                    tmp_file = os.path.join("/ads/{}".format(ad.id), path)
                    instace = AdvertImages(advert=ad, type=media_type,  image=tmp_file)
                    instace.save()
                    logger.info("image {} created for the advertisement ID {}".format(instace, ad.id))
                else:
                    continue
        return ad

class AdvertImagesForm(forms.ModelForm):
    class Meta:
        model= AdvertImages
        fields= ['image','advert', 'type', 'is_approved']


class AdvertVideoForm(forms.ModelForm):
    video = forms.FileField(required=True)
    class Meta:
        model= Advert
        fields= ['video']

apps/adverts/views.py
import json
import base64
import tempfile

import requests
import  logging
from django.conf import settings
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.forms import model_to_dict
from django.http import JsonResponse, HttpResponseRedirect, HttpResponse, Http404
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import View
from django.shortcuts import render, redirect, get_object_or_404
from apps.adverts.constants import AdvertStatus
from apps.adverts.forms import AdvertCreateForm, AdvertVideoForm
from apps.adverts.instagram import Instagram
from apps.adverts.models import Advert, AdvertImages
from django.contrib.auth.decorators import login_required
from apps.payment.models import Subscription


logger = logging.getLogger('main')


def get_as_base64(url):
    with tempfile.NamedTemporaryFile() as tfile:
        tfile.write(requests.get(url).content)
        with open(tfile.name, "rb") as imageFile:
            strng = base64.b64encode(imageFile.read())
        tfile.flush()
    return strng.decode("utf-8")


@login_required
def subscribe(request, pk):
    user = request.user
    try:
        ad_to_pay = Advert.objects.get(user=user, pk=pk)
    except ObjectDoesNotExist:
        return redirect("404")
    request.session['ad_to_pay'] = ad_to_pay.id
    ad_step = request.session.get('ad_step',None)
    if ad_step:
        if ad_step.get('ad_id', None) == pk:
            if ad_step.get('next_step') == 'locations':
                return redirect('locations')
            elif ad_step.get('next_step') == 'sub-plans':
                loc = ad_step.get('loc_selected')
                return redirect(reverse('sub-plans', kwargs={"pk": pk})+'?loc_id={}'.format(loc))
            elif ad_step.get('next_step') == 'confrim_pay':
                return redirect('confrim_pay', package_id=ad_step.get('package_id'))
    return redirect('locations')



@login_required()
def ad_redirect(request):
    try:
        del request.session['ad_to_pay']
    except:
        pass
        logger.info("No ad found in session skiping delete")
    return HttpResponseRedirect('/ad/')

def check_subscription(item):
    subs = item.subscription_set.filter(is_active=True)
    if subs.count():
        return subs.latest('created_ts')
    else:
        return False

@login_required
def adv_list(request):
    user = request.user
    ads = Advert.objects.all().order_by('created_ts')
    ads = ads.filter(user=user).prefetch_related('user')
    page = request.GET.get('page', 1)
    paginator = Paginator(ads, settings.PAGE_SIZE)
    try:
        ads = paginator.page(page)
    except PageNotAnInteger:
        ads = paginator.page(1)
    except EmptyPage:
        ads = paginator.page(paginator.num_pages)

    ad_list = []
    for item in ads:
        item_dict = model_to_dict(item)
        item_dict['currently_susbscribed'] = check_subscription(item)
        item_dict['status'] = item.get_status_display()
        item_dict['created_ts'] = item.created_ts
        ad_list.append(item_dict)
    ad_list = sorted(ad_list, key=lambda x: x['created_ts'], reverse=True)
    return  render(request, 'ad-listing.html', locals())


def get_insta_callback_link(request):
    domain = request.build_absolute_uri('/')[:-1]
    return "{}{}".format(domain, reverse('insta_callback'))


@login_required
def edit_ad(request, ad_id=None):
    try:
        ad = get_object_or_404(Advert, id=ad_id)
        form = AdvertCreateForm(instance=ad)
        # disabled the start_date field on request
        form.fields.get('start_date').disabled = True
        image_set = ad.image_set.all()
        insta_link = "https://api.instagram.com/oauth/authorize?app_id={}&redirect_uri={}&scope=user_profile,user_media&state=1&response_type=code"\
            .format(settings.INSTA_APP_ID, get_insta_callback_link(request))
        return render(request, 'ad-create.html', {
            'ad_id': ad.id,
            'form': form,
            'insta_link': insta_link,
            'image_set': json.dumps([item.image.url for item in image_set]),
            'from_edit': True
        })
    except Exception as e:
        logger.critical("Exception occured %s", str(e))
        raise Http404


@method_decorator(login_required,  name='dispatch')
class AdView(View):
    form_class = AdvertCreateForm
    template_name = 'ad-create.html'
    def get(self, request):
        ad_to_pay = request.session.get('ad_to_pay', None)
        edit = True
        ad_id = None
        if ad_to_pay:
            ad = Advert.objects.get(id=ad_to_pay)
            form = self.form_class(instance=ad)
            ad_id = ad_to_pay
            image_set = json.dumps([item.image.url for item in ad.image_set.all()])
        else:
            form = self.form_class()
            edit = False
            image_set = None
        insta_link = "https://api.instagram.com/oauth/authorize?app_id={}&redirect_uri={}&scope=user_profile,user_media&state=1&response_type=code"\
            .format(settings.INSTA_APP_ID, get_insta_callback_link(request))

        return render(request, self.template_name, {
            'edit': edit,
            'ad_id': ad_id,
            'form': form,
            'insta_link': insta_link,
            'image_set': image_set,
            'dummy_link': reverse('insta_callback')
        })

    def post(self, request):
        redirect_to_list = False
        request_data = request.POST.copy()
        request_data['user'] = request.user.id
        ad_id = request.POST.get('ad_id', None)
        if ad_id:
            request_data.pop('ad_id')
            ad = Advert.objects.get(id=int(ad_id))
            request_data['start_date'] = ad.start_date
            form = self.form_class(request_data, request.FILES, instance=ad)
            request.session['ad_edit'] = {"ad_id": ad.id, 'edit': True}
        else:
            form = self.form_class(request_data)
        if not request.POST.get('images'):
            form.add_error('images', 'Images are required')
        if form.is_bound and form.is_valid():
            if form.instance.pk:
                redirect_to_list = True
                instance = form.instance
                instance.image_set.all().delete()
                if instance.status in [AdvertStatus.Approved, AdvertStatus.Rejected]:
                    instance.status = AdvertStatus.Requested
            else:
                form.instance.status = AdvertStatus.Pending
            instance = form.save()
            instance.save()
            request.session['ad_to_pay'] = instance.id
            request.session['ad_step'] = { "ad_id": instance.id, "next_step": "locations"}
            if redirect_to_list:
                del request.session['ad_edit']
                return HttpResponseRedirect(reverse('adverts_list'))
            return HttpResponseRedirect('/locations/')
        else:
            return render(request, self.template_name, {'form':form, 'ad_id': ad_id })

@login_required
def ad_details(request, ad_id):
    ad = Advert.objects.get(id=ad_id)
    medias = ad.image_set.all()
    sub = check_subscription(ad)
    return render(request, 'ad-details.html', locals())

@login_required
def ad_delete(request, pk):
    try:
        advert = get_object_or_404(Advert, pk=pk)
        x, y = advert.delete()
        messages.add_message(request, messages.ERROR, 'Advert {} deleted '.format(pk))
        return redirect(reverse('adverts_list'))
    except ObjectDoesNotExist:
        messages.add_message(request, messages.ERROR, 'Advert with id{} does not exists'.format(pk))
        return redirect(reverse('adverts_list'))


@login_required
def upload_video(request, pk):
    advert = get_object_or_404(Advert, pk=pk)
    form = AdvertVideoForm(request.POST, request.FILES, instance=advert)
    if form.is_bound and form.is_valid():
        instace = form.save()
        advert.status = AdvertStatus.Approved
        advert.save()
        messages.add_message(request, messages.INFO, "Video Uploaded successfully")
        return HttpResponseRedirect(reverse('campaign-list'))
    return HttpResponseRedirect(reverse('campaign-details',  kwargs={'pk': pk}))


@login_required
def approve_media(request, pk):
    try:
        media = get_object_or_404(AdvertImages, pk=pk)
        media.is_approved=True
        media.save()
        message = "Media Approved successfully"
        return JsonResponse({"message": message, "media_id": pk}, status=200)
    except:
        return JsonResponse({
            "message": "Something went wrong !",
            "media_id": pk,
            "is_last": False
        }, status=500)


@login_required
def reject_media(request, pk):
    try:
        data = json.loads(request.body)
        media = get_object_or_404(AdvertImages, pk=pk)
        advert = media.advert
        media.is_rejected=True
        media.reject_reason = data.get('reject_id')
        media.save()
        advert.is_approved=False
        advert.status = AdvertStatus.Rejected
        message = "Media Approved successfully"
        advert.save()
        return JsonResponse({"message": message, "media_id": pk}, status=200)
    except:
        return JsonResponse({
            "message": "Something went wrong !",
            "media_id": pk
        }, status=500)



@login_required
def broadcast_advert(request, pk):
    try:
        ad = get_object_or_404(Advert, pk=pk)
        status = request.POST.get('status')
        print("status received is=======>  %s" % status)
        status = int(status.strip())
        if status == 5:
            reverse_state = 6

apps/adverts/templates/ad-create.html
{% extends 'panel_base.html' %}

{% block maincontent %}
    {% load static %}
    <div class="maincontent clearfix">
        <div class="form-wizard-wrapper">
          <ul>
            <li><a class="form-wizard-link active" href="javascript:;" data-attr="info"><span>1. create ad</span></a></li>
            <li><a class="form-wizard-link" href="javascript:;" data-attr="ads"><span>2. select screen location</span></a></li>
            <li><a class="form-wizard-link" href="javascript:;" data-attr="placement"><span>3. select subscription plan</span></a></li>
            <li><a class="form-wizard-link" href="javascript:;" data-attr="schedule"><span>4. billing detail</span></a></li>
          </ul>
        </div>
        <div class="infodetail">
          <p>Please fill in the details</p>
        <form method="post" novalidate action="{% url 'ad-view' %}" enctype="multipart/form-data">
        {% csrf_token %}
        {% if from_edit %}
            <input type="hidden"  name="redirect_url" value="{% url 'adverts_list' %}">
        {% endif %}
            {{ form.non_field_errors }}
              {% for hidden_field in form.hidden_fields %}
                {{ hidden_field.errors }}
                {{ hidden_field }}
              {% endfor %}
          <div class="md-form mb-4">
            <label data-error="wrong" data-success="right" for="id_ad_title">Ad Title</label>
                {% if ad_id %}
                <input type="hidden" name="ad_id" value="{{ad_id}}"/>
                {% endif %}
              <input placeholder="Enter Ad Title (e.g. Uber_eats_branding_London)"
                     class="form-control {% if form.ad_title.errors %} has_danger {% endif %}"
                     id="id_ad_title"
                     maxlength="255"
                     name="ad_title"
                     required="required"
                     value="{% if form.ad_title.value %} {{ form.ad_title.value }}{% endif %}"
                     type="text" />
              <span>{{ form.ad_title.errors }}</span>
          </div>
          <div class="md-form mb-4">
            <label data-error="wrong" data-success="right" for="id_ad_description">Ad Description</label>
            <textarea  placeholder="Enter key message / text content you want to show in your ad"
                       class="form-control rounded-0 {% if form.ad_description.errors %} has_danger {% endif %}"
                       id="id_ad_description"
                       rows="10" cols="40"
                       name="ad_description"
                       required="">{% if form.ad_description.value %}{{ form.ad_description.value }}{% endif %}</textarea>
            <span>{{ form.ad_description.errors }}</span>
          </div>
           <div class="datepicker mb-4">
             <label for="start_date">Select the date you want to start your ad campaign</label>
                    {{form.start_date}}
            <span>{{ form.start_date.errors }}</span>
           </div>
          <div class="md-form mb-4">
            <label data-error="wrong" data-success="right" for="defaultForm-pass">Upload high quality image or video to display on your ad</label>
               <div class="md-form mb-4 uploadform">
                  <span>Recommended formates: JPEG, JPG, PNG & MP4</span>
                  <div class="file-field">
                    <input name="images" id="images" type="file" accept="application/octet-stream,image/*,video/mp4,video/x-m4v,video/*"/>
                    <div class="or">or</div>
                    <div class="instabtndiv">
                      <span onclick="openRequestedPopup('{{ insta_link }}')" class="instabtn">Import from Instagram</span>
                    </div>
                  </div>
              </div>
              <span class="alert-danger">{{ form.images.errors }}</span>
            <div class="submitbar" role="group">
                <button type="submit" class="doohmabtn active">Submit</button>
                <a href="{% url 'adverts_list' %}"  type="reset" class="canscelbtn">Cancel</a>
              </div>
          </div>
         </form>
        </div>
      </div>

{% endblock %}

{% block extrajs %}
    <script>
    var images = $('#images');
    {% if image_set %}
    var image_set = {{ image_set|safe }};
    {% endif %}
    [
        {supported: 'Symbol' in window, fill: 'https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.6.15/browser-polyfill.min.js'},
        {supported: 'Promise' in window, fill: 'https://cdn.jsdelivr.net/npm/promise-polyfill@8/dist/polyfill.min.js'},
        {supported: 'fetch' in window, fill: 'https://cdn.jsdelivr.net/npm/fetch-polyfill@0.8.2/fetch.min.js'},
        {supported: 'CustomEvent' in window && 'log10' in Math && 'sign' in Math &&  'assign' in Object &&  'from' in Array &&
                    ['find', 'findIndex', 'some', 'includes'].reduce(function(previous, prop) { return (prop in Array.prototype) ? previous : false; }, true), fill: 'https://unpkg.com/filepond-polyfill/dist/filepond-polyfill.js'}
    ].forEach(function(p) {
        if (p.supported) return;
        document.write('<script src="' + p.fill + '"><\/script>');
    });
    $("input[name='start_date']").datepicker({
            minDate: 0,
            dateFormat: "yy-mm-dd"
        });
    $(function(){
        // Turn input element into a pond with configuration options
        $.fn.filepond.registerPlugin(FilePondPluginFileEncode);
        $.fn.filepond.registerPlugin(FilePondPluginFileValidateType);
        images.filepond({
            allowMultiple: true,
            acceptedFileTypes: ['image/png']
        });
        if (image_set){
            console.log(image_set);
            image_set.forEach(function (item) {
                (async function() {
                    let blob = await fetch(item).then(
                    r => r.blob()
                    );
                    let dataUrl = await new Promise(resolve => {
                      let reader = new FileReader();
                      reader.onload = () => resolve(reader.result);
                      reader.readAsDataURL(blob);
                    });
                    // now do something with `dataUrl`
                    images.filepond('addFile', dataUrl).then(function(file){
                      console.log('file added', file);
                    });
                })();
            });
        }
        // Listen for addfile event
        $('#images').on('FilePond:addfile', function(e) {
            console.log('file added event', e);
        });
        $('form').submit(function () {
           $('#images')
        });
    });

    var windowObjectReference;
    function openRequestedPopup(url) {
      windowObjectReference = window.open(
        url,
        "instagram",
        "height=500,width=500,modal=yes,alwaysRaised=yes,left=500,top500"
      );
    }
    function popUpHandler(val) {
        console.log(val);
        val.forEach(function (item) {
            (async function() {
                let blob = await fetch(item).then(r => r.blob());
                let dataUrl = await new Promise(resolve => {
                  let reader = new FileReader();
                  reader.onload = () => resolve(reader.result);
                  reader.readAsDataURL(blob);
                });
                // now do something with `dataUrl`
                images.filepond('addFiles', dataUrl).then(function(file){
                  console.log('file added', file);
                });
            })();
        });
        console.log("called from popup window with val:==> "+val)
    }
    </script>
{% endblock %}

apps/adverts/templates/ad-listing.html
{% extends 'panel_base.html' %}

{% block body-css %} tablepage {% endblock %}
{% block maincontent %}
    {% load static %}
    <div class="maincontent clearfix">
        <h1>AD LISTING</h1>
        <div class="creatbtnhead">
          <a href="{% url 'ad-new' %}"><button class="creatad">
              <img src="{% static 'images/plus-whight.png' %}" alt="create-image">Create AD</button></a>
        </div>
        <div class="datatable">
          <div class="table-responsive">
            <table class="table">
              <thead>
                <tr>
                  <th scope="col">Sr#</th>
                  <th scope="col">Title</th>
                  <th scope="col">Subscription</th>
                  <th scope="col">Start Date</th>
                  <th scope="col">Expire Date</th>
                  <th scope="col">Status</th>
                  <th scope="col">Action</th>
                </tr>
              </thead>
              <tbody>
              {% if ad_list %}
                  {% for ad in ad_list %}
                    <tr>
                      <th scope="row">{{ forloop.counter0|add:ads.start_index }}</th>
                      <td>{{ad.ad_title}}</td>
                      <td> {% if ad.currently_susbscribed %} £{{ad.currently_susbscribed.package.cost }} {% else %} N/A {% endif %}</td>
                      <td>{% if not ad.start_date %} N/A {% else %} {{ad.start_date}} {% endif %}</td>
                      <td> {% if not ad.end_date %} N/A {% else %} {{ad.end_date|date:"M d, Y"}} {% endif %}</td>
                      <td class='{% if ad.status == "Approved" %} approved {% elif ad.status == "Requested" %} pending {% elif ad.status == 'Rejected' %} rejected {% endif %}'>
                           {{ad.status}} </td>
                      <td>
                        <a href="{% url 'ad-edit' ad_id=ad.id %}" class="viewbtn"><i class="fas fa-edit"></i></a>
                          {% if ad.currently_susbscribed %}
    <!--                        <a href="{% url 'delete-ad'  pk=ad.id %}" class="viewbtn"><i class="fa fa-trash" aria-hidden="true"></i></a>-->
                                <a href="{% url 'ad-details'  ad_id=ad.id %}" class="viewbtn"><i class="fa fa-eye" aria-hidden="true"></i></a>
                          {% else %}
                            <a {% if not ad.currently_susbscribed %} href="{% url 'subscribe' pk=ad.id %}" {% endif %}  class="viewbtn">
                                <i class="fa fa-credit-card" aria-hidden="true"></i>
                            </a>
                          {% endif %}
                      </td>
                    </tr>
                  {% endfor %}
              {% else %}
                  <tr>
                      <td class="text-center" colspan="7">No Ads Created</td></tr>
              {% endif %}
              </tbody>
            </table>
          </div>
          <div class="tablepagination">
            <nav aria-label="Page navigation example">
              <ul class="pagination pg-blue">
                {% if ads.has_previous %}
                    <li class="page-item ">
                        <a class="page-link left-arrow" href="?page={{ ads.previous_page_number }}" tabindex="-1">
                        <img src="{% static 'images/left-pagination.png' %}" alt="Left"></a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ ads.number|add:'-1'}}">{{ ads.number|add:'-1'}}</a>
                    </li>
                {% endif %}
                  <li class="page-item active">
                  <a class="page-link">{{ads.number}}<span class="sr-only">(current)</span></a>
                </li>
                {% if ads.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ ads.number|add:'1'}}">{{ ads.number|add:'1'}}</a>
                    </li>
                    <li class="page-item ">
                        <a class="page-link right-arrow" href="?page={{ ads.next_page_number }}">
                        <img src="{% static 'images/right-pagination.png' %}" alt="Left"></a>
                    </li>
                {% endif %}
              </ul>
            </nav>
          </div>
        </div>
      </div>
{% endblock %}

apps/adverts/templates/insta_gallary.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Select images</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/image-picker.css' %}"/>
    <style>
        .image_picker_image { width: 200px;}
    </style>
</head>
<body>
    <label for="image-picker">Select up to 5 images</label>
    <select id="image-picker" multiple="multiple" class="image-picker masonry show-html">
        {% for image in all_medias %}
            <option data-img-src="{{ image.media_url }}" value="{{ image.media_url }}">Cute Kitten 1</option>
        {% endfor %}
    </select>
    <button class="doohmabtn" onclick="submitUrls()">Done</button>
    <script src="{% static  'js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'js/image-picker.js' %}"></script>
    <script>
        $("select").imagepicker({
            hide_select : true,
            show_label  : false,
        });
        function submitUrls(){
            var dataUrls = [];
            var picker_obj = $("select").data('picker').selected_values();
            if(picker_obj.length <=0) {
                alert("please select atleast one photo to submit");
                return;
            }
            window.opener.popUpHandler(picker_obj);
            window.close();
        }
    </script>
</body>
</html>