apps/payment/urls.py
from django.urls import path
from apps.payment import views as payment_view

urlpatterns = [
    path('plans', payment_view.PlanView.as_view(), name='plan-list'),
    path('plan/create', payment_view.create_plan, name='plan-create'),
    path('plan/<int:pk>/edit', payment_view.manage_plan, name='plan-edit'),
    path('plan/<int:pk>/delete', payment_view.delete_plan, name='plan-delete'),
    path("locations/", payment_view.locations, name="locations"),
    path("pay/", payment_view.locations, name="pay"),
    path("payment-success/", payment_view.payment_success, name="pay-success"),
    path("confirm_pay/<int:package_id>", payment_view.confirm_pay, name="confrim_pay"),
]

doohma/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from apps.common import views as common_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('doohma_admin/', include('apps.doohma_admin.urls')),
    path('', include('apps.common.urls')),
    path('', include('apps.adverts.urls')),
    path('', include('apps.payment.urls')),
    url('^', include('django.contrib.auth.urls')),
    path('account/', include('apps.user.urls')),
    path('api/v1/', include('apps.api.urls')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    url(r'^404/',common_views.render_404, name="404")


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/payment/models.py
import os
from django.utils.translation import ugettext_lazy as _
from django.contrib.postgres.fields import JSONField
from django.db import models
from apps.adverts.models import Advert
from apps.common.base_model import BaseModel
from apps.payment.constants import VideoQualityTypes, BooleanTypes


class Locations(BaseModel):
    name = models.CharField(max_length=255)
    lat = models.DecimalField(max_digits=11, decimal_places=9)
    lng = models.DecimalField(max_digits=11, decimal_places=9)
    image = models.ImageField(upload_to='locations/', blank=True, null=True)
    address = models.TextField()
    google_link = models.URLField(blank=True)
    footfall = models.CharField(max_length=255, blank=True)


    class Meta:
        db_table = "dh_locations"
        verbose_name_plural = "Locations"

    @property
    def get_image(self):
        """
        returns the url of the user avatar
        :return:
        """
        try:
            return self.image.url
        except ValueError:
            return None

class SubscriptionPlans(BaseModel):
    title = models.CharField(max_length=50)
    screens = models.PositiveIntegerField()
    location = models.ManyToManyField(Locations, related_name='locations')
    duration = models.DurationField(blank=True, null=True)
    per_month_quota = models.PositiveIntegerField(blank=True, null=True)
    changes_allowed = models.PositiveIntegerField(blank=True, null=True)
    is_analytics = models.BooleanField(default=False)
    is_app_allowed = models.PositiveSmallIntegerField(choices=BooleanTypes.get_choices(), default=BooleanTypes.NO)
    validity = models.PositiveIntegerField("Validity(Days)", blank=True, null=True)
    cost = models.FloatField(default=0.0)
    video_quality = models.PositiveSmallIntegerField(choices=VideoQualityTypes.get_choices(), default=VideoQualityTypes.HD)
    allow_static_ad_design = models.PositiveSmallIntegerField(choices=BooleanTypes.get_choices(), default=BooleanTypes.NO)
    allow_static_ad_design_count = models.PositiveIntegerField(default=0, blank=True, null=True)
    allow_video_ad_design_count = models.PositiveIntegerField(default=0, blank=True, null=True)
    allow_video_ad_design = models.PositiveSmallIntegerField(choices=BooleanTypes.get_choices(), default=BooleanTypes.NO)
    broadcast_allowance = models.CharField(max_length=255, blank=True, null=True)


    def __str__(self):
        return "{}".format(self.title)

    class Meta:
        db_table = "dh_subscriptions_plans"
        verbose_name_plural = "Subscriptions Plans"


class Subscription(BaseModel):
    package = models.ForeignKey(SubscriptionPlans, on_delete=models.SET_NULL, null=True, blank=True)
    advert = models.ForeignKey(Advert, on_delete=models.SET_NULL, null=True, related_name='subscription_set')
    start_date = models.DateTimeField(auto_now_add=True)
    end_date = models.DateTimeField(blank=True, null=True)
    renewal_date = models.DateTimeField(blank=True, null=True)
    gateway_response = JSONField(blank=True, null=True)
    plan_details = JSONField("Plan Allocated")
    is_active = models.BooleanField(default=True)
    is_recurrent = models.BooleanField(_("Auto Debit"), default=False)


    class Meta:
        db_table = "dh_subscriptions"
        verbose_name_plural = "Subscriptions"

apps/payment/forms.py
from django import forms

from apps.payment.constants import VideoQualityTypes, BooleanTypes
from apps.payment.models import SubscriptionPlans


class LocForm(forms.Form):
    loc_id = forms.IntegerField(required=True)


class PlanForm(forms.ModelForm):

    video_quality = forms.ChoiceField(widget=forms.RadioSelect(),
        choices=VideoQualityTypes.get_choices(),

    )
    allow_static_ad_design = forms.ChoiceField(
        choices=BooleanTypes.get_choices(),
        widget=forms.RadioSelect()
    )
    allow_video_ad_design = forms.ChoiceField(
        choices=BooleanTypes.get_choices(),
        widget=forms.RadioSelect()
    )
    is_app_allowed = forms.ChoiceField(
        choices=BooleanTypes.get_choices(),
        widget=forms.RadioSelect()
    )

    class Meta:
        model = SubscriptionPlans
        fields = (
            "title",
            "screens",
            "duration",
            "per_month_quota",
            "changes_allowed",
            "is_analytics",
            "is_app_allowed",
            "cost",
            "video_quality",
            "allow_static_ad_design",
            "allow_static_ad_design_count",
            "allow_video_ad_design_count",
            "allow_video_ad_design",
            "broadcast_allowance",
        )

    def clean(self):
        cleaned_data = super(PlanForm, self).clean()
        if cleaned_data.get('allow_static_ad_design') == '1':
            if not cleaned_data.get('allow_static_ad_design_count'):
                self.add_error('allow_static_ad_design_count', "Static ad design Count Required")
        if cleaned_data.get('allow_video_ad_design') == '1':
            if not cleaned_data.get('allow_video_ad_design_count'):
                self.add_error('allow_video_ad_design_count', "Video ad design Count Required")
        return cleaned_data

apps/payment/views.py
import logging

import stripe
from datetime import datetime, timedelta
from django.conf import settings
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required, user_passes_test, permission_required
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.core.exceptions import ImproperlyConfigured, ObjectDoesNotExist
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.forms import model_to_dict
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.urls import reverse
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views import View

from apps.adverts.constants import AdvertStatus
from apps.adverts.models import Advert
from apps.payment.forms import PlanForm
from apps.payment.models import Locations, SubscriptionPlans, Subscription
from apps.payment.permissions import user_passes_admin

stripe.api_key = settings.STRIPE_SECRET_KEY # new

logger = logging.getLogger('api')

REDIRECT_FIELD_NAME = 'next'

def is_admin_user(user):
    if not (user.is_authenticated and user.is_staff):
        return False
    return user.is_authenticated and user.is_staff

def admin_required(function=None, redirect_field_name=REDIRECT_FIELD_NAME, login_url=None):
    """
    Decorator for views that checks that the user is logged in, redirecting
    to the log-in page if necessary.
    """
    actual_decorator = user_passes_test(
        lambda u: u.is_authenticated,
        login_url=login_url,
        redirect_field_name=redirect_field_name
    )
    if function:
        return actual_decorator(function)
    return actual_decorator


@login_required
def locations(request):
    locations = Locations.objects.all()
    page = request.GET.get('page', 1)
    paginator = Paginator(locations, settings.PAGE_SIZE)
    try:
        locs = paginator.page(page)
    except PageNotAnInteger:
        locs = paginator.page(1)
    except EmptyPage:
        locs = paginator.page(paginator.num_pages)
    ad_to_pay = request.session['ad_to_pay']
    if ad_to_pay:
        request.session['ad_step'] = {"ad_id": ad_to_pay, "next_step": "plans"}

    return render(request, 'locations.html', locals())

@login_required
def subscription_plans(request, pk):
    try:
        ad_edit = request.session.get('ad_edit')
        if ad_edit.get('ad_id') == pk and ad_edit.get('edit'):
            request.session['ad_edit'] = {"ad_id": pk, 'edit': False}
            return HttpResponseRedirect(reverse('adverts_list'))
    except:
        logger.info("By passing the redirect as ad is created")
    loc_id = request.GET.get('loc_id', None)
    try:
       sel_loc = Locations.objects.get(id=int(loc_id))
    except:
        messages.add_message(request, messages.ERROR, 'No Such location exists')
        return redirect("locations")
    request.session['loc_selected'] =  sel_loc.id
    request.session['ad_id'] = pk
    request.session['ad_step'] = {"ad_id": pk, 'loc_selected':sel_loc.id,  "next_step": "sub-plans"}
    plans = SubscriptionPlans.objects.all().order_by('id')
    key = settings.STRIPE_PUBLISHABLE_KEY
    return render(request, 'sub_plans.html', locals())


@login_required
def confirm_pay(request, package_id):
    sub_plan = get_object_or_404(SubscriptionPlans, pk=package_id)
    location = get_object_or_404(Locations, pk=request.session['loc_selected'])
    advert = get_object_or_404(Advert, pk=request.session['ad_id'])
    request.session['ad_step'] = {"package_id": package_id, "ad_id": request.session['ad_id'], "next_step": "confrim_pay"}

    if request.method == "GET":
        if advert.is_paid:
            plan = advert.subscription_set.latest('created_ts')
            if plan.end_date > timezone.now():
                if plan.package.id == package_id:
                    return HttpResponseRedirect(reverse('adverts_list'))
        try:
            key = settings.STRIPE_PUBLISHABLE_KEY
            # count validity if there is else count 30 days
            validity = sub_plan.validity if sub_plan.validity else 30
            end_date = datetime.now()+ timedelta(days=validity)
            try:
                if advert.start_date:
                    end_date = advert.start_date + timedelta(days=validity)
            except:
                pass
            return render(request, 'confirm_and_pay.html', locals())
        except:
            messages.add_message(request, messages.ERROR, 'Payment Compromized')
            return HttpResponseRedirect(reverse('subscribe', kwargs={'pk': 1}))
    else:
        try:
            sub_plan = get_object_or_404(SubscriptionPlans, pk=package_id)
            validity = sub_plan.validity if sub_plan.validity else 30
            charge = stripe.Charge.create(
                amount=round(sub_plan.cost*100),
                currency="gbp",
                description=sub_plan.title,
                source=request.POST['stripeToken']
            )
            if charge:
                details = charge.to_dict()
                advert.subscription_set.filter(is_active=True).update(is_active=False)
                auto_renew =  request.POST.get('auto_renew')
                sub = Subscription.objects.create(
                    package=sub_plan,
                    advert=advert,
                    gateway_response=charge.to_dict(),
                    plan_details={
                        "title": sub_plan.title,
                        "screens": sub_plan.screens,
                        "duration": 0,
                        "per_month_quota": sub_plan.per_month_quota,
                        "is_analytics": sub_plan.is_analytics,
                        "validity": sub_plan.validity,
                        "cost":sub_plan.cost,
                        "is_recurrent": True if auto_renew == "on" else False,
                        "location": [item.id for item in sub_plan.location.all()]
                    },
                    is_recurrent =True if auto_renew == "on" else False,
                    created_by=request.user,
                    updated_by=request.user,
                    is_active=True,
                    start_date=datetime.now(),
                    end_date=datetime.now() + timedelta(days=validity),
                    renewal_date=datetime.now()+ timedelta(days=validity-5))
                advert.is_paid = True
                advert.end_date = None if auto_renew == "on" else (datetime.now() + timedelta(days=validity)).strftime("%Y-%m-%d")
                advert.status = AdvertStatus.Requested
                advert.save()
                logger.info("deleting ad key from session")
                # messages.add_message(request, messages.SUCCESS, 'Payment completed Successfully')
                return HttpResponseRedirect(reverse('pay-success'))
        except Exception as e:
            logger.critical("Exception caught", exc_info=True)
            messages.add_message(request, messages.ERROR, str(e))
            return HttpResponseRedirect(reverse('confrim_pay', kwargs={"package_id": package_id}))

@login_required
def payment_success(request):
    return render(request, 'thank-you.html', locals())


class PlanView(UserPassesTestMixin, LoginRequiredMixin, View):

    create_template = 'create-plan.html'
    list_template = 'plan-list.html'
    model_form = PlanForm
    login_url = '/doohma_admin/login'
    permission_denied_message = 'Admin access level is required to access this view'

    def get_login_url(self):
        """
        Override this method to override the login_url attribute.
        """
        login_url = self.login_url or settings.LOGIN_URL
        if not login_url:
            raise ImproperlyConfigured(
                '{0} is missing the login_url attribute. Define {0}.login_url, settings.LOGIN_URL, or override '
                '{0}.get_login_url().'.format(self.__class__.__name__)
            )

        return str(login_url)

    def test_func(self):
        user = self.request.user
        if not user.is_authenticated and user.is_staff:
            logout(self.request)
        return user.is_authenticated and user.is_staff

    def get(self, request, pk=None):
        plans = SubscriptionPlans.objects.all().order_by('-id')
        page = request.GET.get('page', 1)
        paginator = Paginator(plans, settings.PAGE_SIZE)
        try:
            plans = paginator.page(page)
        except PageNotAnInteger:
            plans = paginator.page(1)
        except EmptyPage:
            plans = paginator.page(paginator.num_pages)
        return render(request, self.list_template, locals())

@login_required
@user_passes_admin(is_admin_user)
def manage_plan(request, pk):
    if not request.user.is_superuser:
        return HttpResponseForbidden()
    if request.method == 'GET':
        plan = get_object_or_404(SubscriptionPlans, pk=pk)
        form = PlanForm(instance=plan)
        return render(request, 'create-plan.html', {"form": form})

    if request.method == 'POST':
        plan =  get_object_or_404(SubscriptionPlans, pk=pk)
        form = PlanForm(request.POST, instance=plan)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('plan-list'))
        return render(request, 'create-plan.html', {'form': form})

    if request.method == 'DELETE':
        plan = get_object_or_404(SubscriptionPlans, pk=pk)
        plan.delete()
        return reverse('plan-list')


@login_required
@user_passes_admin(is_admin_user)
def create_plan(request):
    if request.method == "POST":
        form = PlanForm(request.POST)

apps/payment/templates/create-plan.html
{% extends 'panel_base.html' %}
{% block body-css %} tablepage {% endblock %}
{% block maincontent %}
    {% load static %}
    <div class="maincontent">
    {% with url_name=request.resolver_match.url_name %}
        {% if url_name == 'plan-create' %}
            <h1>Create New Plan</h1>
        {% else %}
            <h1>Edit Plan {{ form.title.value }}</h1>
        {% endif %}
    {% endwith %}
        <div class="plansdetailform">
            <form method="post" action="" novalidate>
                {% csrf_token %}
                {{ form.non_field_errors }}
                <!-- form card register -->
                <div class="card card-outline-secondary">
                    <div class="card-body">
                        <div class="form">
                            <div class="row form-group">
                                <div class="col-md-4">
                                    <label>Name of Plan</label>
                                </div>
                                <div class="col-md-8">
                                    <input class="form-control"
                                           name="title"
                                           placeholder="Name of Plan"
                                           type="text"
                                            {% if form.title.value %}
                                                value="{{ form.title.value }}
                                            {% endif %}"/>
                                    <span>{{ form.title.errors }}</span>
                                </div>
                            </div>
                            <div class="row form-group">
                                <div class="col-md-4">
                                    <label>Price per Month</label>
                                </div>
                                <div class="col-md-8">
                                    <input class="form-control"
                                            {% if form.cost.value %}
                                                value="{{ form.cost.value }}"
                                            {% endif %}
                                           name="cost"
                                           placeholder="Price per Month"
                                           required=""
                                           type="number"/>
                                    <span>{{ form.cost.errors }}</span>
                                </div>
                            </div>
                            <div class="row form-group">
                                <div class="col-md-4">
                                    <label>Broadcast Allowance</label>
                                </div>
                                <div class="col-md-8">
                                    <input class="form-control"
                                           name="broadcast_allowance"
                                            {% if form.broadcast_allowance.value %}
                                           value="{{ form.broadcast_allowance.value }}"
                                            {% endif %}
                                           placeholder="Broadcast Allowance"
                                           type="text"/>
                                    <span>{{ form.broadcast_allowance.errors }}</span>
                                </div>
                            </div>
                            <div class="row form-group">
                                <div class="col-md-4">
                                    <label>No of Ad Design changes</label>
                                </div>
                                <div class="col-md-8">
                                    <input class="form-control"
                                           name="changes_allowed"
                                            {% if form.changes_allowed.value %}
                                            value="{{ form.changes_allowed.value }}"
                                            {% endif %}
                                           placeholder="changes_allowed"
                                           type="text"/>
                                    <span>{{ form.changes_allowed.errors }}</span>
                                </div>
                            </div>
                        </div>
                        <div class="row form-group">
                            <div class="col-md-4">
                                <label>No of Screens</label>
                            </div>
                            <div class="col-md-8">
                                <input class="form-control"
                                        {% if form.screens.value %}
                                       value="{{ form.screens.value }}"
                                        {% endif %}
                                       name="screens"
                                       placeholder="No of Screens"
                                       type="number" />
                                <span>{{ form.screens.errors }}</span>
                            </div>
                        </div>
                        <div class="row form-group">
                            <div class="col-md-4">
                                <label>Video Quality</label>
                            </div>
                            <div class="col-md-8 rad-input-div">
                                 {{ form.video_quality }}
                            <span>{{ form.video_quality.errors }}</span>
                            </div>
                        </div>
                        <div class="row form-group">
                            <div class="col-md-4">
                                <label> Allow Static Ad Design</label>
                            </div>
                            <div class="col-md-8">
                                <div class="yesorno rad-input-div">
                                    {{ form.allow_static_ad_design }}
                                <span>{{ form.allow_static_ad_design.errors }}</span>
                                </div>
                                <div class="textinput">
                                    <div class="form-group" id="id_allow_static_ad_design">
                                        <input class="form-control"
                                               name="allow_static_ad_design_count"
                                               placeholder="how much time"
                                               {% if form.allow_static_ad_design.value %}
                                                value="{{ form.allow_static_ad_design_count.value}}"
                                               {% endif %}
                                               type="number">
                                        <span>{{ form.allow_static_ad_design_count.errors }}</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row form-group">
                            <div class="col-md-4">
                                <label for="inputVerify3"> Allow Video Ad Design</label>
                            </div>
                            <div class="col-md-8">
                                <div class="yesorno rad-input-div">
                                    {{ form.allow_video_ad_design }}
                                <span>{{ form.allow_video_ad_design.errors }}</span>
                                </div>
                                <div class="textinput">
                                    <div class="form-group" id="id_allow_video_ad_design">
                                        <input class="form-control"
                                           name="allow_video_ad_design_count"
                                           placeholder="how much time"
                                            {% if form.allow_video_ad_design.value %}
                                            value="{{ form.allow_video_ad_design_count.value}}"
                                           {% endif %}
                                           required=""
                                           type="number"/>
                                    <span>{{ form.allow_video_ad_design_count.errors }}</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row form-group">
                            <div class="col-md-4">
                                <label for="inputVerify3">Android App Access</label>
                            </div>
                            <div class="col-md-8">
                                <div class="yesorno rad-input-div">
                                    {{ form.is_app_allowed }}
                                <span>{{ form.is_app_allowed.errors }}</span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group" style="text-align: center;">
                                {% with url_name=request.resolver_match.url_name %}
                                <input class="doohmabtn"
                                       style="height: unset !important;"
                                       type="submit"
                                       value="{% if url_name == 'plan-edit' %} Update {% else %} Create {% endif %}"/>
                                {% endwith %}
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}
{% block extrajs %}
    <script>
          $(document).ready(function () {
              var static_ad_design_yes  = $("#id_allow_static_ad_design_0");
              var video_ad_design_yes = $("#id_allow_video_ad_design_0");
              var input_static_ad_design_count =  $("input[name='allow_static_ad_design_count']");
              var input_video_ad_design_count = $("input[name='allow_video_ad_design_count']");
              input_static_ad_design_count.hide();
              input_video_ad_design_count.hide();

              if(static_ad_design_yes.is(':checked')){
                  input_static_ad_design_count.show()
              };
              if(video_ad_design_yes.is(':checked')){
                  input_video_ad_design_count.show()
              };

              $("input[name='video_quality']:checked").parent().addClass('radio_checked');
              $("input[name='allow_static_ad_design']:checked").parent().addClass('radio_checked');
              $("input[name='allow_video_ad_design']:checked").parent().addClass('radio_checked');
              $("input[name='is_app_allowed']:checked").parent().addClass('radio_checked');

              $("input[name='video_quality']").click(function () {
                $("input[name='video_quality']").parents().removeClass('radio_checked');
                $(this).parent().addClass('radio_checked');
              });
               $("input[name='allow_static_ad_design']").click(function () {
                   debugger;
                   if ($(this).val() === '1'){
                        input_static_ad_design_count.show()
                   } else {
                       input_static_ad_design_count.hide()
                   }
                $("input[name='allow_static_ad_design']").parents().removeClass('radio_checked');
                $(this).parent().addClass('radio_checked');
              });
               $("input[name='allow_video_ad_design']").click(function () {
                   if ($(this).val() === '1'){
                        input_video_ad_design_count.show()
                   } else {
                       input_video_ad_design_count.hide()
                   }
                $("input[name='allow_video_ad_design']").parents().removeClass('radio_checked');
                $(this).parent().addClass('radio_checked');
              });
               $("input[name='is_app_allowed']").click(function () {
                $("input[name='is_app_allowed']").parents().removeClass('radio_checked');
                $(this).parent().addClass('radio_checked');
              });
          })
        </script>
{% endblock %}

apps/payment/templates/plan-list.html
{% extends 'panel_base.html' %}
{% block body-css %} admin-registerd {% endblock %}
{% block maincontent %}
{% load static %}
    <div class="maincontent">
        <h1>Manage Plans</h1>
        <div class="creatbtnhead">
          <a class="creatad" href="{% url 'plan-create' %}">
              <img src="{%  static  'images/plus-whight.png' %}" alt="add">Create Plan</a>
        </div>
        <div id="creattable">
          <div class="table-responsive">
            <table class="table">
              <thead>
                <tr>
                  <th scope="col">Sr#</th>
                  <th scope="col">Plan Name</th>
                  <th scope="col">Price</th>
                  <th scope="col">Action</th>
                </tr>
              </thead>
              <tbody>
              {% for plan in plans %}
                <tr>
                  <td>{{forloop.counter}}</td>
                  <td>{{ plan.title }}</td>
                    <td>£ {{ plan.cost }}<sup>*</sup></td>
                    <td>
                        <a href="{% url 'plan-edit' pk=plan.id %}" ><i class="fas fa-pencil-alt"></i></a>
                        <a href="{% url 'plan-delete' pk=plan.id %}"><i class="fas fa-trash"></i></a>
                    </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
{% endblock %}